name:                sudokuSolver
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/TomCathelain/sudokuSolver#readme
license:             BSD-3-Clause
author:              TOM CATHELAIN
#maintainer:
copyright:           2025 TOM CATHELAIN
#category:

dependencies:
  - base >= 4.7 && < 5

library:
  source-dirs: src

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

executables:
  sudokuSolver:
    source-dirs:      src
    main:             Main.hs
    dependencies:
      - base
